# Generated by Django 3.0.5 on 2020-05-30 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200530_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('video', models.FileField(blank=True, null=True, upload_to='media/movies')),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Movie',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='viewmovie',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Movie'),
        ),
    ]
