# Generated by Django 3.0.5 on 2020-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20200530_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Silver', 'silver'), ('Gold', 'gold'), ('Free', 'free')], default='Free', max_length=50),
        ),
    ]
