# Generated by Django 3.0.5 on 2020-05-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20200530_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.Membership'),
        ),
    ]
