# Generated by Django 3.0.5 on 2020-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_auto_20200530_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
