# Generated by Django 3.0.5 on 2020-06-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_auto_20200601_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
