# Generated by Django 3.0.5 on 2020-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
