# Generated by Django 3.0.5 on 2020-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_usermembership_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Hollywood', 'Hollywood'), ('Bollywood', 'Bollywood'), ('Dual audio', 'Dual audio'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=20),
        ),
    ]
